### Exercícios

#### Exercício 1

In [1]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 45.9 ms
Wall time: 1.27 s


#### Exercício 2

In [2]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

#### Exercício 3

In [4]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

#### Exercício 4

In [6]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Imprima os elementos da terceira linha da matriz
arr2d[2]

array([7, 8, 9])

In [8]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

#### Exercício 5

In [9]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### Exercício 6

In [11]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [12]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [13]:
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

#### Exercício 7

In [14]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


#### Exercício 8

In [16]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [17]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

#### Exercício 9

In [18]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [19]:
data = resp.json()
data[0]['title']

'TST: Verify isin returns consistent results for passed iterables'

In [20]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    50443  TST: Verify isin returns consistent results fo...   
1    50442  BUG: Using datetime global in query expression...   
2    50441            REF: share TimedeltaArray division code   
3    50440  BUG: Fix issue where df.groupby.resample.size ...   
4    50439  CLN, TST: clean up and increase coverage in ts...   
5    50437  BUG: Series(pyarrow-backed).round raising Attr...   
6    50436  TST: Make get_array smarter to work for masked...   
7    50435   BUG: inconsistent handling of exact=False cas...   
8    50433                                      CLN: Assorted   
9    50432                        ENH: Add lazy copy to align   
10   50431             ENH: Add lazy copy for drop duplicates   
11   50429                      ENH: Use lazy copy for dropna   
12   50428                ENH: Use lazy copy in infer objects   
13   50427  BUG: `xticklables` is not correctly set when u...   
14   50426                      ENH: Use cow for reindex_like   
15   50425         REF: Make Util functions accessible from C   
16   50424    PDEP6: ban upcasting in setitem-like operations   
17   50417  TST: Add test for Period construction from str...   
18   50416  CLN: Use exclusions in determination of _selec...   
19   50415                   Add cow mechanism to rename_axis   
20   50414  BUG: Grouper specified by key not regarded as ...   
21   50413  BUG: Grouper specified by key not regarded as ...   
22   50412  BUG: inconsistent handling of exact=False case...   
23   50411  Datetime parsing (PDEP-4): allow mixture of IS...   
24   50410  Datetime parsing (PDEP-4): should time strings...   
25   50409  BUG: Read_csv won't warn/skip bad lines when n...   
26   50408          STYLE: prohibit parsing exeption messages   
27   50407            DEPR: Unnecessary kwargs in groupby ops   
28   50406  ENH: Use explicit arguments in DataFrameGroupB...   
29   50405                 DEPR: axis argument in groupby ops   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2                                                  []  open  
3                                                  []  open  
4   [{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4ND...  open  
5   [{'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMz...  open  
6                                                  []  open  
7   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
8                                                  []  open  
9                                                  []  open  
10                                                 []  open  
11                                                 []  open  
12                                                 []  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14                                                 []  open  
15                                                 []  open  
16  [{'id': 4253279386, 'node_id': 'LA_kwDOAA0YD87...  open  
17  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
18  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
19                                                 []  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4ND...  open  
24  [{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4ND...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26                                                 []  open  
27  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
28  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
29  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open

#### Exercício 10

In [21]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [22]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [23]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [24]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5